### ISSUE TITLE
Allow configuration of environment variables for the runtime environment

### ISSUE THREAD

**Issue by nuest** [o2r-project/erc-spec#64]
```yml
id: b9b0099e-9f8d-4a33-8acf-cb0c062efaec
version: 1
execution:
  environment:
    - TZ=CET
```

The only option for `run` is `environment` to set environment variables inside containers as defined in [docker-compose](https://docs.docker.com/compose/environment-variables/#setting-environment-variables-in-containers).
Environment variables are defined as a list of strings.
Key and value are separated by `=`.

The environment variables SHOULD be used to fix settings out of control of the contained code that can hinder successful ERC [checking](../glossary.md#check), e.g. by setting a time zone to avoid issues during checking.
